name: Github pages deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      env:
        CI: true
        GITHUB_PAGES_TOKEN: ${{ secrets.GITHUB_PAGES_TOKEN }}
      run: |
        npm install
        npm run docs:build --if-present
        cd docs/.vuepress/dist
        git init
        git config user.name zhaoye
        git config user.email zy81218@gmail.com
        git remote add origin https://{$GITHUB_PAGES_TOKEN}@github.com/zhaoye/zhaoye.github.io.git
        git add -A
        git commit -m "deploy"
        git push origin master -f
        cd -
