name: Github pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run docs:build --if-present
        cd docs/.vuepress/dist
        git init
        git add -A
        git commit -m "deploy"
        git config --global user.name zhaoye
        git config --global user.email zy81218@gmail.com
        git push -f git@github.com:zhaoye/zhaoye.github.io.git master
        cd -
      env:
        CI: true
